### ISSUE TITLE
Find the origin of an error message

### ISSUE THREAD

**Issue by reduzent** [pd-externals/tipoftheday-plugin#20] opened 2022-06-10 19:21 UTC
### Detail

```plain text
If you see an error in the Pd console and you're wondering what triggered it, you can Ctrl-click the message to bring the patch window to the front that contains the object in question. The object is marked blue.
```

**Comment by umlaeute** [comment] 2022-06-10 20:14
isn't this somewhat a duplicate of https://deken.puredata.info/tipoftheday-plugin/tips/find-lines/?

or do you think it's important to stress the "Error finding" feature more?

(while thinking about it, it's probably not a bad thing to have very similar tips: it spotlights a given feature from multiple perspectives)

**Comment by reduzent** [comment] 2022-06-10 21:08
> isn't this somewhat a duplicate of https://deken.puredata.info/tipoftheday-plugin/tips/find-lines/?

Yes. I probably should read all existing tips before posting new ones. :-)

> or do you think it's important to stress the "Error finding" feature more?

No.

**Closed** 2022-06-11 18:40 UTC
Labels: automated tip
